name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

jobs:
  dist-windows-x86_64:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
      - name: Build Rune
        shell: cmd
        run: |
          odin build src -out:bin/rune.exe -define:VERSION=${{ github.event.inputs.version }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows-x86_64_windows
          path: ./bin