name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

jobs:
  dist-windows-x86_64:
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build Rune
        run: |
          mkdir dist
          odin build src -out:dist/rune.exe -define:VERSION=${{ github.event.inputs.version }}
          cp .\README.md dist\
      - name: Run tests
        run: |
          .\dist\rune.exe test
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows-x86_64-${{ github.event.inputs.version }}
          path: .\dist
  
  dist-darwin-arm64:
    runs-on: macos-latest
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build Rune
        run: |
          mkdir dist
          odin build src -out:dist/rune -define:VERSION=${{ github.event.inputs.version }}
          cp ./README.md dist/
      - name: Run tests
        run: |
          ./dist/rune test
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-darwin-arm64-${{ github.event.inputs.version }}
          path: ./dist

  dist-darwin-x86_64:
    runs-on: macos-13
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build Rune
        run: |
          mkdir dist
          odin build src -out:dist/rune -define:VERSION=${{ github.event.inputs.version }}
          cp ./README.md dist/
      - name: Run tests
        run: |
          ./dist/rune test
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-darwin-x86_64-${{ github.event.inputs.version }}
          path: ./dist

  dist-linux-x86_64:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build Rune
        run: |
          mkdir dist
          odin build src -out:dist/rune -define:VERSION=${{ github.event.inputs.version }}
          cp ./README.md dist/
      - name: Run tests
        run: |
          ./dist/rune test
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-linux-x86_64-${{ github.event.inputs.version }}
          path: ./dist
