name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

jobs:
  dist-windows-x86_64:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Rune
        shell: cmd
        run: |
          mkdir dist
          odin build src -out:dist/rune.exe -define:VERSION=${{ github.event.inputs.version }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows-x86_64_windows
          path: ./dist